import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'
import Categories from '../../components/Categories'
import FeaturedProducts from '../../components/FeaturedProducts'
import AllProducts from '../../components/AllProducts'
import Footer from '../../components/Footer'
import axios from 'axios';

interface Product {
  _id: string;
  name: string;
  desc: string;
  category: string;
  section: string;
  price: number;
  image: string;
  featured: boolean;
}

interface HomeProps {
  featuredProducts: Product[];
  allProducts: Product[]; 
}

export default function Home({ featuredProducts, allProducts }: HomeProps) {
  return (
    <>
      <div className='bg-bgColor text-white w-full z-50'>
        <Head>
          <title>Time Totes</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <>
          <Navbar />
          <Hero />
          <Categories />
          <FeaturedProducts products={featuredProducts} />
          <AllProducts products={allProducts} />
          <Footer />
        </>
      </div>
    </>
  )
};

export async function getServerSideProps() {
  try {
    const { data } = await axios.get(`https://e-shop-unty.vercel.app/api/products`);

    return {
      props: {
        featuredProducts: data,
        allProducts: data,
      }
    }
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      props: {
        featuredProducts: [],
        allProducts: [],
      }
    };
  }
}
